### ISSUE TITLE
pip install radiopadre doesn't work

### ISSUE THREAD

**Issue by o-smirnov** [radio-astro/radiopadre#28]
Do the requirements need to be updated?

```
sudo pip install radiopadre
[sudo] password for oms: 
Downloading/unpacking radiopadre
  Downloading radiopadre-0.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/radiopadre/setup.py) egg_info for package radiopadre
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/radiopadre/setup.py", line 3, in <module>
        from radiopadre import __version__
      File "radiopadre/__init__.py", line 5, in <module>
        import astropy
    ImportError: No module named astropy
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/radiopadre/setup.py", line 3, in <module>

    from radiopadre import __version__

  File "radiopadre/__init__.py", line 5, in <module>

    import astropy

ImportError: No module named astropy
```

**Comment by o-smirnov** [comment]
Actually even with ``astropy`` manually installed, it bombs out with:

```
oms@ray:~$ sudo pip install radiopadre
Downloading/unpacking radiopadre
  Downloading radiopadre-0.3.tar.gz
  Running setup.py (path:/tmp/pip_build_root/radiopadre/setup.py) egg_info for package radiopadre
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/radiopadre/setup.py", line 20, in <module>
        long_description=read('README.md'),
      File "/tmp/pip_build_root/radiopadre/setup.py", line 7, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/radiopadre/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/radiopadre/setup.py", line 20, in <module>

    long_description=read('README.md'),

  File "/tmp/pip_build_root/radiopadre/setup.py", line 7, in read

    return open(os.path.join(os.path.dirname(__file__), fname)).read()

IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/radiopadre/README.md'

----------------------------------------
Cleaning up...
```
